In [1]:
import torch

In [5]:
torch.tensor(55)
scalar = torch.tensor(55)
scalar

tensor(55)

In [7]:
scalar.dim()

0

In [11]:
scalar.shape

torch.Size([])

In [12]:
scalar.item()

55

In [13]:
scalar.shape

torch.Size([])

In [15]:
vector = torch.tensor([1, 2, 3])
vector.shape

torch.Size([3])

In [16]:
vector.dim()

1

In [17]:
torch.rand(size=(30, 10))

tensor([[0.0086, 0.5538, 0.7504, 0.2091, 0.3364, 0.3801, 0.3129, 0.9591, 0.2780,
         0.2288],
        [0.2099, 0.5013, 0.7572, 0.9901, 0.0602, 0.9984, 0.4344, 0.6416, 0.1867,
         0.6489],
        [0.3554, 0.0030, 0.7150, 0.5632, 0.9989, 0.2278, 0.4122, 0.8923, 0.3545,
         0.6787],
        [0.8755, 0.5167, 0.6189, 0.8173, 0.6484, 0.3257, 0.6428, 0.1383, 0.4187,
         0.2599],
        [0.5241, 0.7239, 0.8394, 0.6891, 0.8345, 0.9628, 0.8799, 0.9766, 0.8651,
         0.8732],
        [0.9657, 0.0015, 0.2245, 0.5783, 0.5438, 0.3707, 0.1127, 0.4941, 0.6836,
         0.3466],
        [0.2495, 0.9856, 0.6186, 0.8346, 0.3417, 0.4720, 0.1286, 0.5418, 0.8394,
         0.0201],
        [0.3012, 0.4965, 0.7230, 0.3636, 0.2544, 0.7122, 0.5694, 0.9697, 0.2614,
         0.5329],
        [0.5350, 0.2124, 0.6599, 0.2933, 0.4122, 0.6820, 0.8999, 0.4708, 0.9136,
         0.5749],
        [0.7857, 0.6781, 0.5219, 0.3247, 0.7880, 0.7739, 0.5515, 0.0071, 0.5837,
         0.6239],
        [0

In [18]:
vector.numpy()

array([1, 2, 3])

In [24]:
torch.zeros(size=(3, 5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
torch.ones(size=(3, 5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [25]:
vector.tolist()

[1, 2, 3]

In [26]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix.tolist()

[[1, 2, 3], [4, 5, 6]]

In [28]:
torch.arange(2, 10).dtype

torch.int64

In [33]:
vector = torch.tensor([[1.,3.,5.], [7.,9.,11.]], requires_grad=True, device="cpu")

In [34]:
vector.grad

In [35]:
vector1 = torch.tensor([[1.,3.,5.], [7.,9.,11.]])
vector2 = torch.tensor([[1.,3.,5.], [7.,9.,11.]])

In [36]:
torch.matmul(vector1, vector2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [44]:
vector1.max(), vector2.min(), vector.argmax(dim=1)

(tensor(11.), tensor(1.), tensor([2, 2]))

In [45]:
index = vector.argmax()
torch.unravel_index(index, vector.shape)

(tensor(1), tensor(2))

In [46]:
vector1.contiguous()

tensor([[ 1.,  3.,  5.],
        [ 7.,  9., 11.]])

In [47]:
vector1.is_contiguous()

True

In [49]:
torch.stack((vector1, vector2), dim=0)

tensor([[[ 1.,  3.,  5.],
         [ 7.,  9., 11.]],

        [[ 1.,  3.,  5.],
         [ 7.,  9., 11.]]])

In [50]:
torch.stack((vector1, vector2), dim=1)

tensor([[[ 1.,  3.,  5.],
         [ 1.,  3.,  5.]],

        [[ 7.,  9., 11.],
         [ 7.,  9., 11.]]])

In [60]:
import torch.nn as nn
import torch.nn.functional  as F

class IrisClassification(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4, 1)
    
    def forward(self, x):
        x = x.reshape(-1, 4)
        output = F.relu(self.linear(x), inplace=True)
        return output
    


In [61]:
device = "cpu"
model = IrisClassification().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [62]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[-0.3649,  0.0150,  0.1911, -0.1114]])),
             ('linear.bias', tensor([-0.3005]))])

In [63]:
from torchsummary import summary
summary(model, (1, 4))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                    [-1, 1]               5
Total params: 5
Trainable params: 5
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [ ]:
# Training
model.train()
num_epoch = 10
running_loss = 0
correct = 0
total = 0
for epoch in range(1, num_epoch+1):
    
    #FP
    prediction = model(x)
    loss = criterion(prediction, y)

    # BP
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Metrics
    running_loss += loss*x.size(0)
    _, predicted_class = prediction.max(1)
    correct += predicted_class.eq(x).sum().item()
    total += x.size(0)
    

In [65]:
model = nn.Sequential(
        nn.Conv2d(3, 64, 7, stride=2),
        nn.BatchNorm2d((1,1)),
        nn.ReLU(),
        nn.Conv2d(64, 64, 3),
        nn.BatchNorm2d((1,1)),
        nn.Sigmoid()
)

In [ ]:
for layer in model:
    if hasattr(layer, "weight") and layer.weight is not None:
        print(layer.weight)
        print("\n")
    if hasattr(layer, "bias") and layer.bias is not None:
        print(layer.bias)
        print("\n")
    

Parameter containing:
tensor([[[[-4.8642e-02,  6.9436e-04, -5.9131e-02,  ...,  3.0764e-02,
            1.3112e-02, -3.8074e-02],
          [-6.4995e-02, -1.9950e-03, -6.2453e-02,  ...,  6.9200e-02,
            4.6936e-02, -2.1371e-02],
          [-4.4116e-03, -5.1812e-02,  3.2731e-02,  ...,  1.5321e-02,
           -2.4859e-02,  5.3121e-02],
          ...,
          [ 4.5806e-02, -5.0397e-02,  3.7417e-02,  ...,  6.8711e-02,
            1.1926e-02, -3.0256e-02],
          [-3.9526e-02,  6.3543e-02,  3.0541e-02,  ...,  3.8710e-02,
           -3.7262e-02,  6.7446e-03],
          [ 8.1409e-02,  1.5275e-02,  8.0501e-03,  ...,  2.8322e-02,
           -6.4198e-02, -5.3588e-02]],

         [[-3.0905e-02, -4.7240e-02, -3.1640e-02,  ..., -6.2007e-02,
            2.8818e-02, -2.9639e-02],
          [ 2.1910e-02,  3.4598e-02,  2.3780e-02,  ...,  3.3503e-02,
            3.4600e-02,  6.5620e-02],
          [ 7.0242e-02,  2.9624e-02,  6.7898e-02,  ..., -1.6024e-02,
            2.1230e-02, -3.6179e-02]

AttributeError: 'Conv2d' object has no attribute 'trainable'