In [3]:
import torch
import torch.nn as nn

## Sequential way of creating model

In [32]:
X = torch.rand(10, 20)

In [36]:
model_sequential = nn.Sequential(
    nn.Linear(in_features=20, out_features=64),
    nn.ReLU(),
    nn.Linear(in_features=64, out_features=32),
    nn.ReLU(),
    nn.Linear(in_features=32, out_features=5),
    nn.Softmax()
)

In [37]:
model_sequential

Sequential(
  (0): Linear(in_features=20, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=5, bias=True)
  (5): Softmax(dim=None)
)

In [38]:
y_predict = model_sequential(X)
y_predict

d:\SW\anaconda3\envs\CV_krish\Lib\site-packages\torch\nn\modules\module.py:1736: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([[0.1974, 0.1851, 0.1907, 0.2001, 0.2267],
        [0.1975, 0.1844, 0.1941, 0.2011, 0.2228],
        [0.1957, 0.1841, 0.1955, 0.2027, 0.2220],
        [0.1947, 0.1850, 0.1950, 0.1992, 0.2261],
        [0.1961, 0.1843, 0.1944, 0.2017, 0.2235],
        [0.1970, 0.1816, 0.1918, 0.1974, 0.2322],
        [0.1917, 0.1849, 0.1980, 0.1989, 0.2264],
        [0.1961, 0.1864, 0.1967, 0.1957, 0.2251],
        [0.1995, 0.1815, 0.1842, 0.2102, 0.2246],
        [0.1947, 0.1850, 0.1923, 0.2016, 0.2264]], grad_fn=<SoftmaxBackward0>)

## Functional API approach

In [39]:
class FunctionalModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(20, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 5)
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax()

    def forward(self, X):
        x = self.relu(self.fc1(X))
        x = self.relu(self.fc2(x))
        x = self.relu(self.fc3(x))
        return self.softmax(x)
    


In [40]:
X = torch.rand(10, 20)
functional_model = FunctionalModel()
functional_model(X)

d:\SW\anaconda3\envs\CV_krish\Lib\site-packages\torch\nn\modules\module.py:1736: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([[0.2055, 0.1983, 0.1861, 0.2239, 0.1861],
        [0.2239, 0.1952, 0.1865, 0.2078, 0.1865],
        [0.2115, 0.1916, 0.1841, 0.2287, 0.1841],
        [0.2184, 0.1985, 0.1848, 0.2131, 0.1853],
        [0.2153, 0.2013, 0.1861, 0.2112, 0.1861],
        [0.2146, 0.1935, 0.1832, 0.2255, 0.1832],
        [0.2121, 0.1910, 0.1817, 0.2336, 0.1817],
        [0.2077, 0.1954, 0.1840, 0.2290, 0.1840],
        [0.2214, 0.1923, 0.1869, 0.2133, 0.1861],
        [0.2126, 0.1995, 0.1848, 0.2182, 0.1848]], grad_fn=<SoftmaxBackward0>)

In [ ]:
functional_model.fc1.weight

Parameter containing:
tensor([[ 0.0032,  0.1960,  0.1863,  ...,  0.2212,  0.1866, -0.1925],
        [ 0.1966, -0.0537,  0.1232,  ..., -0.0362, -0.0526,  0.1665],
        [-0.1517, -0.0940, -0.1653,  ..., -0.0931, -0.1899,  0.1225],
        ...,
        [-0.0947,  0.1874, -0.0601,  ...,  0.1713, -0.2084, -0.0739],
        [-0.1197, -0.1719,  0.0094,  ...,  0.0104,  0.1596, -0.1649],
        [-0.0493, -0.0399, -0.0990,  ...,  0.0006,  0.0302, -0.0147]],
       requires_grad=True)

In [46]:
functional_model.parameters()

<generator object Module.parameters at 0x0000027A526E8820>

In [52]:
for layer in functional_model.parameters():
    print(layer)
    if hasattr(layer, "weight") and layer.weight is not None:
        print(layer.weight.data)

Parameter containing:
tensor([[ 0.0032,  0.1960,  0.1863,  ...,  0.2212,  0.1866, -0.1925],
        [ 0.1966, -0.0537,  0.1232,  ..., -0.0362, -0.0526,  0.1665],
        [-0.1517, -0.0940, -0.1653,  ..., -0.0931, -0.1899,  0.1225],
        ...,
        [-0.0947,  0.1874, -0.0601,  ...,  0.1713, -0.2084, -0.0739],
        [-0.1197, -0.1719,  0.0094,  ...,  0.0104,  0.1596, -0.1649],
        [-0.0493, -0.0399, -0.0990,  ...,  0.0006,  0.0302, -0.0147]],
       requires_grad=True)
['H', 'T', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__

In [56]:
functional_model

FunctionalModel(
  (fc1): Linear(in_features=20, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=5, bias=True)
  (relu): ReLU()
  (softmax): Softmax(dim=None)
)

### Multiclass Classification with pytorch

In [58]:
!pip install scikit-learn

  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ------- -------------------------------- 2.1/11.1 MB 10.7 MB/s eta 0:00:01
   ---------------- ----------------------- 4.5/11.1 MB 11.2 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/11.1 MB 11.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.1 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 10.5 MB/s eta 0:00:00
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   -- ------------------------------------- 2.4/44.8 MB 12.3 MB/s eta 0:00:04
   ---- ----------------------------------- 4.7/44.8 MB 11.9 MB/s eta 0:00:04
   ------ --------------------------------- 7.1/44

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch
import torch.nn as nn
import torch.optim as optim

In [40]:
data = load_iris()
X = data["data"]
y = data["target"]

In [41]:
X = torch.tensor(X, dtype=torch.float32).to("cpu")
y = torch.tensor(y, dtype=torch.long).to("cpu")

In [42]:
torch.cuda.is_available()

False

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=45)

In [44]:
type(X_train)

torch.Tensor

In [45]:
scalar = StandardScaler()
X_train_standard = scalar.fit_transform(X_train)
X_test_standard = scalar.fit_transform(X_test)

In [46]:
type(X_test_standard), type(X_train_standard)

(numpy.ndarray, numpy.ndarray)

In [47]:
X_train_standard = torch.tensor(X_train_standard, dtype=torch.float32).to("cpu")
X_test_standard = torch.tensor(X_test_standard, dtype=torch.float32).to("cpu")
type(X_train_standard), type(X_test_standard)

(torch.Tensor, torch.Tensor)

In [48]:
type(y_train), type(y_test)

(torch.Tensor, torch.Tensor)

In [103]:
class IrisDataModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super().__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, num_classes)
        self.softmax = nn.LogSoftmax(dim=1)
        self.relu = nn.ReLU()

    def forward(self, X):
        x = self.relu(self.fc1(X))
        x = self.relu(self.fc2(x))
        return self.softmax(self.fc3(x))

In [104]:
input_size = X_train_standard.shape[1]
hidden_size = 64
num_classes = 3

model = IrisDataModel(input_size, hidden_size, num_classes).to("cpu")
num_epoch = 100
batch_size = 16
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)


In [105]:
for epoch in range(1, num_epoch+1):
    y_predict = model(X_train_standard)
    loss = criterion(y_predict, y_train)
    
    optimizer.zero_grad()
    
    loss.backward()
    
    optimizer.step()

    print(f"epoch: {epoch}, loss: {loss.item():.4f}")

epoch: 1, loss: 1.0209
epoch: 2, loss: 0.8234
epoch: 3, loss: 0.6549
epoch: 4, loss: 0.5132
epoch: 5, loss: 0.4051
epoch: 6, loss: 0.3274
epoch: 7, loss: 0.2689
epoch: 8, loss: 0.2232
epoch: 9, loss: 0.1898
epoch: 10, loss: 0.1636
epoch: 11, loss: 0.1376
epoch: 12, loss: 0.1134
epoch: 13, loss: 0.0953
epoch: 14, loss: 0.0820
epoch: 15, loss: 0.0703
epoch: 16, loss: 0.0626
epoch: 17, loss: 0.0605
epoch: 18, loss: 0.0558
epoch: 19, loss: 0.0507
epoch: 20, loss: 0.0474
epoch: 21, loss: 0.0421
epoch: 22, loss: 0.0381
epoch: 23, loss: 0.0372
epoch: 24, loss: 0.0352
epoch: 25, loss: 0.0326
epoch: 26, loss: 0.0320
epoch: 27, loss: 0.0312
epoch: 28, loss: 0.0291
epoch: 29, loss: 0.0285
epoch: 30, loss: 0.0280
epoch: 31, loss: 0.0264
epoch: 32, loss: 0.0260
epoch: 33, loss: 0.0255
epoch: 34, loss: 0.0242
epoch: 35, loss: 0.0237
epoch: 36, loss: 0.0232
epoch: 37, loss: 0.0222
epoch: 38, loss: 0.0220
epoch: 39, loss: 0.0215
epoch: 40, loss: 0.0207
epoch: 41, loss: 0.0205
epoch: 42, loss: 0.0199
e