In [2]:
import torch

In [2]:
scalar = torch.tensor(55)

In [3]:
scalar.ndim, scalar.shape

(0, torch.Size([]))

In [4]:
vector = torch.tensor([0, 1])
print(vector.ndim)
print(vector.shape)
print(vector.dtype)

1
torch.Size([2])
torch.int64


In [5]:
vector = torch.tensor([0., 1.])
print(vector.ndim)
print(vector.shape)
print(vector.dtype)

1
torch.Size([2])
torch.float32


In [5]:
# Adding ramdom noise image
import cv2
random_image = torch.rand(size=(150,150,3))
random_image1 = random_image * 200
cv2.imshow("Random Noise", random_image1.numpy())
cv2.waitKey()
cv2.destroyAllWindows()


In [6]:
vector = torch.tensor([1, 2, 4], dtype=torch.int64)

In [8]:
vector.type(torch.float64).mean()

tensor(2.3333, dtype=torch.float64)

In [9]:
vector.type(torch.float64).mean().item()

2.3333333333333335

In [11]:
tensor_random = torch.randn(4,4)
tensor_random

tensor([[-0.1768, -0.6557,  1.8454,  0.5167],
        [-0.6049,  0.4611, -0.4150, -1.3875],
        [ 0.6457,  0.3177,  0.6517,  0.6716],
        [-1.9630,  0.3051,  1.1342, -0.3471]])

In [13]:
tensor_random_view_16 = tensor_random.view(16)
tensor_random_view_16

tensor([-0.1768, -0.6557,  1.8454,  0.5167, -0.6049,  0.4611, -0.4150, -1.3875,
         0.6457,  0.3177,  0.6517,  0.6716, -1.9630,  0.3051,  1.1342, -0.3471])

In [15]:
tensor_random_view_8 = tensor_random.view(-1, 8)
tensor_random_view_8

tensor([[-0.1768, -0.6557,  1.8454,  0.5167, -0.6049,  0.4611, -0.4150, -1.3875],
        [ 0.6457,  0.3177,  0.6517,  0.6716, -1.9630,  0.3051,  1.1342, -0.3471]])

In [16]:
tensor_random_view_8 = tensor_random.view(-1, 2)
tensor_random_view_8

tensor([[-0.1768, -0.6557],
        [ 1.8454,  0.5167],
        [-0.6049,  0.4611],
        [-0.4150, -1.3875],
        [ 0.6457,  0.3177],
        [ 0.6517,  0.6716],
        [-1.9630,  0.3051],
        [ 1.1342, -0.3471]])

In [17]:
tensor_random = torch.randn(4,4)
tensor_random_T = tensor_random.T

In [18]:
tensor_random_T.is_contiguous()

False

In [19]:
tensor_random_T.reshape(-1, 4)

tensor([[-1.1455, -1.8829, -0.8723, -0.1316],
        [ 2.4259, -0.2413,  1.2979,  1.1251],
        [-1.0680,  2.4040, -0.7779, -0.5085],
        [ 1.2625, -0.6713,  1.1130,  0.6787]])

In [20]:
tensor_random_T.reshape(-1,)

tensor([-1.1455, -1.8829, -0.8723, -0.1316,  2.4259, -0.2413,  1.2979,  1.1251,
        -1.0680,  2.4040, -0.7779, -0.5085,  1.2625, -0.6713,  1.1130,  0.6787])

In [23]:
tensor_a = torch.randn(2, 3)
tensor_b = torch.randn(2, 3)
print(tensor_a)
print(tensor_b)
torch.stack((tensor_a, tensor_b))

tensor([[ 1.2214, -1.5826,  1.3774],
        [ 1.2178, -0.5318,  0.8103]])
tensor([[-0.0614, -0.7121, -1.4664],
        [-1.6257,  0.0478,  0.3713]])


tensor([[[ 1.2214, -1.5826,  1.3774],
         [ 1.2178, -0.5318,  0.8103]],

        [[-0.0614, -0.7121, -1.4664],
         [-1.6257,  0.0478,  0.3713]]])

In [27]:
dim_stacking = torch.stack((tensor_a, tensor_b), dim=1)
dim_stacking

tensor([[[ 1.2214, -1.5826,  1.3774],
         [-0.0614, -0.7121, -1.4664]],

        [[ 1.2178, -0.5318,  0.8103],
         [-1.6257,  0.0478,  0.3713]]])

In [26]:
dim_stacking.shape

torch.Size([2, 2, 3])

In [28]:
dim_stacking[0]

tensor([[ 1.2214, -1.5826,  1.3774],
        [-0.0614, -0.7121, -1.4664]])

In [29]:
dim_stacking[1]

tensor([[ 1.2178, -0.5318,  0.8103],
        [-1.6257,  0.0478,  0.3713]])

In [32]:
dim_stacking_2 = torch.stack((tensor_a, tensor_b), dim=2)
print(tensor_a)
print(tensor_b)
print(dim_stacking_2)
print(dim_stacking_2.shape)

tensor([[ 1.2214, -1.5826,  1.3774],
        [ 1.2178, -0.5318,  0.8103]])
tensor([[-0.0614, -0.7121, -1.4664],
        [-1.6257,  0.0478,  0.3713]])
tensor([[[ 1.2214, -0.0614],
         [-1.5826, -0.7121],
         [ 1.3774, -1.4664]],

        [[ 1.2178, -1.6257],
         [-0.5318,  0.0478],
         [ 0.8103,  0.3713]]])
torch.Size([2, 3, 2])
